name: Extraer App

on: [push]

jobs:
  extraer-y-guardar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Descomprimir el archivo ZIP
        run: |
          unzip -o TelefonoProLZ.zip -d ./
          rm TelefonoProLZ.zip

      - name: Subir las carpetas al repositorio
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Extraer TelefonoProLZ" || echo "No hay cambios para guardar"
          git push
